package com.glaf.base.modules.sys.model;
// default package

import java.util.Date;

/**
 * MstDepartment generated by MyEclipse Persistence Tools
 */

public class MstDepartment implements java.io.Serializable {

	// Fields

	private int id;
	private int unitId;
	private String unitCode;
	private String description;
	private int parentUnitId;
	private int chiefPositionId;
	private String enabledFlag;
	private int unitLevel;
	private String finUnitCode;
	private String ddlType;
	private Date lastUpdateDate;
	private int treeId;
	private int deptid;

	// Constructors

	public int getDeptid() {
		return deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	public int getTreeId() {
		return treeId;
	}

	public void setTreeId(int treeId) {
		this.treeId = treeId;
	}

	/** default constructor */
	public MstDepartment() {
	}

	/** full constructor */
	public MstDepartment(int unitId, String unitCode, String description,
			int parentUnitId, int chiefPositionId, String enabledFlag,
			int unitLevel, String finUnitCode, String ddlType,
			Date lastUpdateDate) {
		this.unitId = unitId;
		this.unitCode = unitCode;
		this.description = description;
		this.parentUnitId = parentUnitId;
		this.chiefPositionId = chiefPositionId;
		this.enabledFlag = enabledFlag;
		this.unitLevel = unitLevel;
		this.finUnitCode = finUnitCode;
		this.ddlType = ddlType;
		this.lastUpdateDate = lastUpdateDate;
	}

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUnitId() {
		return this.unitId;
	}

	public void setUnitId(int unitId) {
		this.unitId = unitId;
	}

	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getParentUnitId() {
		return this.parentUnitId;
	}

	public void setParentUnitId(int parentUnitId) {
		this.parentUnitId = parentUnitId;
	}

	public int getChiefPositionId() {
		return this.chiefPositionId;
	}

	public void setChiefPositionId(int chiefPositionId) {
		this.chiefPositionId = chiefPositionId;
	}

	public String getEnabledFlag() {
		return this.enabledFlag;
	}

	public void setEnabledFlag(String enabledFlag) {
		this.enabledFlag = enabledFlag;
	}

	public int getUnitLevel() {
		return this.unitLevel;
	}

	public void setUnitLevel(int unitLevel) {
		this.unitLevel = unitLevel;
	}

	public String getFinUnitCode() {
		return this.finUnitCode;
	}

	public void setFinUnitCode(String finUnitCode) {
		this.finUnitCode = finUnitCode;
	}

	public String getDdlType() {
		return this.ddlType;
	}

	public void setDdlType(String ddlType) {
		this.ddlType = ddlType;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}